apiVersion: v1
kind: Namespace
metadata:
  name: elk-logging
  labels:
    name: elk-logging
    app: apm-demo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: elk-logging
data:
  elasticsearch.yml: |
    cluster.name: "apm-elasticsearch"
    network.host: 0.0.0.0
    discovery.type: single-node
    xpack.security.enabled: false
    xpack.monitoring.collection.enabled: true
