apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- ../base/deployment.yaml
- ../base/ingress.yaml
- ../base/hpa.yaml

patchesStrategicMerge:
- deployment-patch.yaml
- ingress-patch.yaml
- hpa-patch.yaml

images:
- name: 273204284763.dkr.ecr.us-east-1.amazonaws.com/apm-backend
  newTag: v1.0.0

commonLabels:
  environment: prod
  
commonAnnotations:
  environment: prod
